# docker-compose.yml
version: '3'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"
  php-server:
    build: 
      context: ./server
      dockerfile: Dockerfile.apache
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: hendektracker
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data: {}