# docker-compose.yml
version: '3'
services:
  react-app:
    container_name: 'hendek-react'
    build: 
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "4023:9080"
    networks:
      - hendek

  api:
    container_name: 'hendek-api'
    build: 
      context: ./server
      dockerfile: Dockerfile.apache
    depends_on:
      - db
    networks:
      - hendek

  db:
    container_name: 'hendek-db'
    image: mysql:5.7
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: hendektracker
    volumes:
      - db_hendek:/var/lib/mysql
    networks:
      - hendek

volumes:
  db_hendek: {}

networks:
  hendek:
     name: hendek-net
     driver: bridge
