# docker-compose.yml
version: '3'
services:
  react-app:
    container_name: 'hendek-react'
    build: 
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "40420:9080"
    networks:
      - hendek
  api:
    container_name: 'hendek-api'
    build: 
      context: ./server
      dockerfile: Dockerfile.apache
    ports:
      - "40422:80"
    depends_on:
      - db
    networks:
      - hendek
  db:
    container_name: 'hendek-db'
    image: mysql:5.7
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: hendektracker
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "40423:3306"
    networks:
      - hendek
volumes:
  db_data: {}

networks:
  hendek:
     name: hendek-net
     driver: bridge
     ipam:
      config:
        - subnet: 10.0.7.0/24
